version: "3"
services:
  mongodb:
    container_name: ${MONGO_DB_NAME}
    image: mongo:6.0
    volumes:
      - poke-vol:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    command: ["--auth"]

  # configuring the db

  # access the db
  mongo-express:
    depends_on:
      - mongodb
    image: mongo-express:1.0.0-alpha.4
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_DB_NAME}
    ports:
      - ${MONGO_ME_PORT_EX}:${MONGO_ME_PORT_IN}
    restart: always

  # mounting the app
  poke-app:
    depends_on:
      - mongodb
      - mongo-express
    image: klerith/pokemon-nest-app:1.0.0
    environment:
      # mongo service we need to call
      MONGODB: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_DB_NAME}:${MONGO_PORT_IN}
      # db that connects to express is the same name that connects to the db
      DB_NAME: ${MONGO_DB_NAME}
    ports:
      - ${APP_PORT_EX}:${APP_PORT_IN}
    restart: always

volumes:
  poke-vol:
    external: false
